import pandas as pd
from collections import Counter
from . import ai_service

def translate_condition_simple(condition: str) -> str:
    simple_translations = {
        'depression': 'Depresyon',
        'anxiety': 'Anksiyete', 
        'pain': 'Ağrı',
        'high blood pressure': 'Yüksek tansiyon',
        'diabetes': 'Diyabet',
        'insomnia': 'Uykusuzluk',
        'migraine': 'Migren',
        'arthritis': 'Artrit',
        'asthma': 'Astım',
        'allergies': 'Alerji',
        'headache': 'Baş ağrısı',
        'nausea': 'Mide bulantısı',
        'infection': 'Enfeksiyon',
        'fever': 'Ateş',
        'cold': 'Soğuk algınlığı',
        'flu': 'Grip',
        'cough': 'Öksürük',
        'weight loss': 'Kilo verme',
        'weight gain': 'Kilo alma',
        'cholesterol': 'Kolesterol',
        'heart disease': 'Kalp hastalığı',
        'cancer': 'Kanser',
        'seizures': 'Nöbet',
        'bipolar disorder': 'Bipolar bozukluk',
        '65+years users found this comment helpful': '65+ yaş kullanıcılar bu yorumu faydalı buldu',
        'prostate cancer': 'Prostat kanseri',
        'not listed / other': 'Listede yok / diğer',
        'hypertension': 'Hipertansiyon',
        'back pain': 'Bel ağrısı',
        'osteoarthritis': 'Osteoartrit',
        'fibromyalgia': 'Fibromiyalji',
        'chronic pain': 'Kronik ağrı',
        'muscle pain': 'Kas ağrısı',
        'joint pain': 'Eklem ağrısı',
        'nerve pain': 'Sinir ağrısı',
        'stomach pain': 'Mide ağrısı',
        'chest pain': 'Göğüs ağrısı',
        'menstrual pain': 'Adet ağrısı',
        'toothache': 'Diş ağrısı',
        'panic disorder': 'Panik bozukluk',
        'generalized anxiety disorder': 'Yaygın anksiyete bozukluğu',
        'social anxiety': 'Sosyal anksiyete',
        'ptsd': 'Travma sonrası stres bozukluğu',
        'ocd': 'Obsesif kompulsif bozukluk',
        'schizophrenia': 'Şizofreni',
        'mania': 'Mani',
        'atrial fibrillation': 'Atrial fibrilasyon',
        'heart failure': 'Kalp yetmezliği',
        'coronary artery disease': 'Koroner arter hastalığı',
        'stroke': 'Felç',
        'blood clots': 'Kan pıhtılaşması',
        'acid reflux': 'Asit refleksi',
        'gerd': 'Gastroözofageal refleks hastalığı',
        'ulcer': 'Ülser',
        'ibs': 'İrritabl bağırsak sendromu',
        'crohns disease': 'Crohn hastalığı',
        'constipation': 'Kabizlik',
        'diarrhea': 'İshal',
        'copd': 'Kronik obstrüktif akciğer hastalığı',
        'pneumonia': 'Zatürre',
        'bronchitis': 'Bronşit',
        'sinusitis': 'Sinüzit',
        'allergic rhinitis': 'Alerjik rinit',
        'eczema': 'Egzama',
        'psoriasis': 'Sedef hastalığı',
        'acne': 'Akne',
        'rash': 'Kızarıklık',
        'dermatitis': 'Dermatit',
        'menopause': 'Menopoz',
        'pms': 'Adet öncesi sendrom',
        'endometriosis': 'Endometriozis',
        'pcos': 'Polikistik over sendromu',
        'pregnancy': 'Hamilelik',
        'uti': 'İdrar yolu enfeksiyonu',
        'kidney stones': 'Böbrek taşı',
        'prostate': 'Prostat',
        'erectile dysfunction': 'Erektil disfonksiyon',
        'thyroid': 'Tiroid',
        'anemia': 'Anemi',
        'osteoporosis': 'Osteoporoz',
        'gout': 'Gut hastalığı',
        'lupus': 'Lupus',
        'multiple sclerosis': 'Multipl skleroz',
        'parkinsons': 'Parkinson',
        'alzheimers': 'Alzheimer',
        'epilepsy': 'Epilepsi',
        'glaucoma': 'Glokom',
        'cataracts': 'Katarakt',
        'bipolar disorder': 'Bipolar Bozukluk',
        'schizoaffective disorder': 'Şizoafektif Bozukluk',
        'vertigo': 'Vertigo',
        'motion sickness': 'Hareket Hastalığı',
        'nausea/vomiting': 'Mide Bulantısı/Kusma',
        'nausea': 'Mide Bulantısı',
        'vomiting': 'Kusma',
        'major depressive disorder': 'Majör Depresif Bozukluk',
        'generalized anxiety disorder': 'Yaygın Anksiyete Bozukluğu',
        'panic disorder': 'Panik Bozukluk',
        'social anxiety disorder': 'Sosyal Anksiyete Bozukluğu',
        'obsessive compulsive disorder': 'Obsesif Kompulsif Bozukluk',
        'post traumatic stress disorder': 'Travma Sonrası Stres Bozukluğu',
        'attention deficit hyperactivity disorder': 'Dikkat Eksikliği Hiperaktivite Bozukluğu',
        'seasonal affective disorder': 'Mevsimsel Duygudurum Bozukluğu',
        'eating disorder': 'Yeme Bozukluğu',
        'sleep disorder': 'Uyku Bozukluğu',
        'substance abuse': 'Madde Bağımlılığı',
        'alcohol dependence': 'Alkol Bağımlılığı',
        'smoking cessation': 'Sigara Bırakma',
        'weight management': 'Kilo Yönetimi',
        'chronic fatigue syndrome': 'Kronik Yorgunluk Sendromu',
        'irritable bowel syndrome': 'İrritabl Bağırsak Sendromu',
        'restless leg syndrome': 'Huzursuz Bacak Sendromu',
        'sleep apnea': 'Uyku Apnesi',
        'narcolepsy': 'Narkolepsi',
        'insomnia': 'Uykusuzluk',
        'jet lag': 'Jet Lag',
        'shift work sleep disorder': 'Vardiya Çalışması Uyku Bozukluğu',
        'rheumatoid arthritis': 'Romatoid Artrit',
        'psoriatic arthritis': 'Psoriatik Artrit', 
        'juvenile arthritis': 'Juvenil Artrit',
        'ankylosing spondylitis': 'Ankilozan Spondilit',
        'osteoarthritis': 'Osteoartrit',
        'gouty arthritis': 'Gut Artriti',
        'reactive arthritis': 'Reaktif Artrit',
        'septic arthritis': 'Septik Artrit',
        'psoriasis': 'Sedef Hastalığı',
        'plaque psoriasis': 'Plak Psoriazis',
        'scalp psoriasis': 'Sakal Derisinde Psoriazis',
        'psoriatic arthritis': 'Psoriatik Artrit',
        'atopic dermatitis': 'Atopik Dermatit',
        'seborrheic dermatitis': 'Seboreik Dermatit',
        'contact dermatitis': 'Kontakt Dermatit',
        'inflammatory bowel disease': 'Enflamatuar Barsak Hastalığı',
        'ulcerative colitis': 'Ülseratif Kolit',
        'crohn\'s disease': 'Crohn Hastalığı',
        'systemic lupus erythematosus': 'Sistemik Lupus Eritematozus',
        'sjogren\'s syndrome': 'Sjögren Sendromu',
        'scleroderma': 'Skleroderma',
        'vasculitis': 'Vasülit',
        'polymyalgia rheumatica': 'Polimiyaljiya Romatika',
        'giant cell arteritis': 'Dev Hücreli Arterit',
        'breast cancer': 'Meme Kanseri',
        'lung cancer': 'Akciğer Kanseri',
        'colon cancer': 'Kolon Kanseri',
        'prostate cancer': 'Prostat Kanseri',
        'ovarian cancer': 'Over Kanseri',
        'leukemia': 'Lösemi',
        'lymphoma': 'Lenfoma',
        'melanoma': 'Melanom',
        'multiple sclerosis': 'Multipl Skleroz',
        'parkinson\'s disease': 'Parkinson Hastalığı',
        'alzheimer\'s disease': 'Alzheimer Hastalığı',
        'huntington\'s disease': 'Huntington Hastalığı',
        'amyotrophic lateral sclerosis': 'Amiyotrofik Lateral Skleroz',
        'myasthenia gravis': 'Miyastenia Gravis',
        'guillain-barre syndrome': 'Guillain-Barré Sendromu',
        'hypothyroidism': 'Hipotiroidizm',
        'hyperthyroidism': 'Hipertiroidizm',
        'diabetes type 1': 'Tip 1 Diyabet',
        'diabetes type 2': 'Tip 2 Diyabet',
        'gestational diabetes': 'Gestasyonel Diyabet',
        'cushing\'s syndrome': 'Cushing Sendromu',
        'addison\'s disease': 'Addison Hastalığı',
        'coronary heart disease': 'Koroner Kalp Hastalığı',
        'myocardial infarction': 'Miyokard Enfarkti',
        'angina': 'Anjina',
        'arrhythmia': 'Aritmi',
        'bradycardia': 'Bradikardi',
        'tachycardia': 'Taşikardi',
        'cardiomyopathy': 'Kardiyomiyopati',
        'adhd': 'DEHB (Dikkat Eksikliği Hiperaktivite Bozukluğu)',
        'opiate dependence': 'Opiyat Bağımlılığı',
        'benign prostatic hyperplasia': 'İyi Huylu Prostat Büyümesi (BPH)',
        'emergency contraception': 'Acil Kontrasepsiyon',
        'bipolar disorder': 'Bipolar Bozukluk',
        'bipolar disorde': 'Bipolar Bozukluk', 
        'epilepsy': 'Epilepsi',
        'birth control': 'Doğum Kontrolü',
        'migraine prevention': 'Migren Önleme',
        'crohn\'s disease': 'Crohn Hastalığı',
        'cough': 'Öksürük',
        'obesity': 'Obezite',
        'major depressive disorder': 'Majör Depresif Bozukluk',
        'generalized anxiety disorder': 'Yaygın Anksiyete Bozukluğu',
        'panic disorder': 'Panik Bozukluk',
        'social anxiety disorder': 'Sosyal Anksiyete Bozukluğu',
        'obsessive compulsive disorder': 'Obsesif Kompulsif Bozukluk',
        'post traumatic stress disorder': 'Travma Sonrası Stres Bozukluğu',
        'attention deficit hyperactivity disorder': 'Dikkat Eksikliği Hiperaktivite Bozukluğu',
        'seasonal affective disorder': 'Mevsimsel Duygudurum Bozukluğu',
        'fibromyalgia': 'Fibromiyalji',
        'chronic pain': 'Kronik Ağrı',
        'neuropathic pain': 'Nöropatik Ağrı',
        'diabetic peripheral neuropathy': 'Diyabetik Periferik Nöropati',
        'postherpetic neuralgia': 'Postherpetik Nöralji',
        'trigeminal neuralgia': 'Trigeminal Nöralji',
        'restless legs syndrome': 'Huzursuz Bacak Sendromu',
        'hot flashes': 'Sıcak Basması',
        'vasomotor symptoms': 'Vazomotor Semptomlar',
        'osteoporosis': 'Osteoporoz',
        'prevention of osteoporosis': 'Osteoporoz Önleme',
        'postmenopausal osteoporosis': 'Postmenopozal Osteoporoz',
        'muscle spasms': 'Kas Spazmı',
        'muscle spasticity': 'Kas Spastisitesi',
        'multiple sclerosis': 'Multipl Skleroz',
        'spinal cord injury': 'Omurilik Yaralanması',
        'cervical dystonia': 'Servikal Distoni',
        'blepharospasm': 'Blefarospazm',
        'hyperhidrosis': 'Hiperhidroz',
        'chronic migraine': 'Kronik Migren',
        'overactive bladder': 'Aşırı Aktif Mesane',
        'urinary incontinence': 'İdrar Kaçırma',
        'neurogenic bladder': 'Nörojenik Mesane',
        'interstitial cystitis': 'Interstisyel Sistit',
        'bladder pain syndrome': 'Mesane Ağrısı Sendromu',
        'chronic fatigue syndrome': 'Kronik Yorgunluk Sendromu',
        'myalgic encephalomyelitis': 'Miyaljik Ensefalomiyelit',
        'irritable bowel syndrome': 'İrritabl Bağırsak Sendromu',
        'gastroparesis': 'Gastroparezi',
        'cyclic vomiting syndrome': 'Siklik Kusma Sendromu',
        'functional dyspepsia': 'Fonksiyonel Dispepsi',
        'gastroesophageal reflux disease': 'Gastroözofageal Refleks Hastalığı',
        'peptic ulcer disease': 'Peptik Ülser Hastalığı',
        'helicobacter pylori infection': 'Helicobacter Pylori Enfeksiyonu',
        'zollinger-ellison syndrome': 'Zollinger-Ellison Sendromu',
        'inflammatory bowel disease': 'Enflamatuar Bağırsak Hastalığı',
        'ulcerative colitis': 'Ülseratif Kolit',
        'microscopic colitis': 'Mikroskopik Kolit',
        'pouchitis': 'Puşit',
        'short bowel syndrome': 'Kısa Bağırsak Sendromu',
        'celiac disease': 'Çölyak Hastalığı',
        'lactose intolerance': 'Laktoz Intoleransı',
        'small intestinal bacterial overgrowth': 'Küçük Bağırsak Bakteriyel Aşırı Büyümesi',
        'diverticulitis': 'Divertikülit',
        'diverticular disease': 'Divertiküler Hastalık',
        'anal fissure': 'Anal Fissür',
        'hemorrhoids': 'Hemoroid',
        'pilonidal cyst': 'Pilonidal Kist',
        'perianal fistula': 'Perianal Fistül',
        'high blood pressure': 'Yüksek Tansiyon',
        'hypertension': 'Hipertansiyon',
        'type 2 diabetes': 'Tip 2 Diyabet',
        'diabetes mellitus': 'Diabetes Mellitus',
        'high cholesterol': 'Yüksek Kolesterol',
        'hyperlipidemia': 'Hiperlipidemi',
        'atrial fibrillation': 'Atriyal Fibrilasyon',
        'heart failure': 'Kalp Yetmezliği',
        'coronary artery disease': 'Koroner Arter Hastalığı',
        'stroke prevention': 'Felc Önleme',
        'deep vein thrombosis': 'Derin Ven Trombozu',
        'pulmonary embolism': 'Pulmoner Emboli',
        'blood clots': 'Kan Pıhtılaşması',
        'anticoagulation': 'Antikoagülasyon',
        'thrombosis prevention': 'Tromboz Önleme',
        'venous thromboembolism': 'Venöz Tromboembolizm',
        'peripheral artery disease': 'Periferik Arter Hastalığı',
        'intermittent claudication': 'Aralıklı Topallama',
        'raynaud\'s phenomenon': 'Raynaud Fenomeni',
        'varicose veins': 'Varis Damarları',
        'chronic venous insufficiency': 'Kronik Venöz Yetmezlik',
        'lymphedema': 'Lenfödem',
        'cellulitis': 'Sellit',
        'skin infection': 'Cilt Enfeksiyonu',
        'wound infection': 'Yara Enfeksiyonu',
        'abscess': 'Apse',
        'folliculitis': 'Folikülit',
        'impetigo': 'Impetigo',
        'erysipelas': 'Erizipel',
        'necrotizing fasciitis': 'Nekrotizan Fasiit',
        'osteomyelitis': 'Osteomiyelit',
        'septic arthritis': 'Septik Artrit',
        'endocarditis': 'Endokardit',
        'meningitis': 'Menenjit',
        'encephalitis': 'Ensefalit',
        'brain abscess': 'Beyin Apsesi',
        'subdural empyema': 'Subdural Ampiyem',
        'epidural abscess': 'Epidural Apse',
        'spinal cord abscess': 'Omurilik Apsesi',
        'discitis': 'Diskit',
        'vertebral osteomyelitis': 'Vertebral Osteomiyelit',
        'prosthetic joint infection': 'Protez Eklem Enfeksiyonu',
        'catheter-related infection': 'Kateter İlişkili Enfeksiyon',
        'central line infection': 'Santral Hat Enfeksiyonu',
        'bloodstream infection': 'Kan Dolaşımı Enfeksiyonu',
        'sepsis': 'Sepsis',
        'septic shock': 'Septik Şok',
        'bacteremia': 'Bakteriyemi',
        'fungemia': 'Fungemi',
        'candidemia': 'Kandidemi',
        'aspergillosis': 'Aspergillozis',
        'histoplasmosis': 'Histoplazmozis',
        'coccidioidomycosis': 'Koksidioidomikozis',
        'blastomycosis': 'Blastomikozis',
        'cryptococcosis': 'Kriptokokozis',
        'pneumocystis pneumonia': 'Pneumocystis Pnömonisi',
        'toxoplasmosis': 'Toksoplazmozis',
        'cytomegalovirus infection': 'Sitomegalovirüs Enfeksiyonu',
        'herpes simplex': 'Herpes Simpleks',
        'herpes zoster': 'Herpes Zoster',
        'varicella': 'Su Çiçeği',
        'epstein-barr virus': 'Epstein-Barr Virüsü',
        'human immunodeficiency virus': 'İnsan Bağışıklık Yetmezliği Virüsü',
        'hiv infection': 'HIV Enfeksiyonu',
        'aids': 'AIDS',
        'hepatitis a': 'Hepatit A',
        'hepatitis b': 'Hepatit B',
        'hepatitis c': 'Hepatit C',
        'hepatitis d': 'Hepatit D',
        'hepatitis e': 'Hepatit E',
        'chronic hepatitis': 'Kronik Hepatit',
        'acute hepatitis': 'Akut Hepatit',
        'liver cirrhosis': 'Karaciğer Sirozu',
        'liver failure': 'Karaciğer Yetmezliği',
        'hepatic encephalopathy': 'Hepatik Ensefalopati',
        'portal hypertension': 'Portal Hipertansiyon',
        'esophageal varices': 'Özofagus Varisleri',
        'ascites': 'Asit',
        'spontaneous bacterial peritonitis': 'Spontan Bakteriyel Peritonit',
        'hepatorenal syndrome': 'Hepatorenal Sendrom',
        'wilson\'s disease': 'Wilson Hastalığı',
        'hemochromatosis': 'Hemokromatozis',
        'alpha-1 antitrypsin deficiency': 'Alfa-1 Antitripsin Eksikliği',
        'primary biliary cholangitis': 'Primer Bilier Kolanjit',
        'primary sclerosing cholangitis': 'Primer Sklerozlayn Kolanjit',
        'autoimmune hepatitis': 'Otoimmun Hepatit',
        'drug-induced liver injury': 'İlaç Kaynaklı Karaciğer Hasarı',
        'alcoholic liver disease': 'Alkolik Karaciğer Hastalığı',
        'non-alcoholic fatty liver disease': 'Non-alkolik Yağlı Karaciğer Hastalığı',
        'non-alcoholic steatohepatitis': 'Non-alkolik Steatohepatit',
        'gallstones': 'Safra Taşı',
        'cholelithiasis': 'Kolelitiyazis',
        'cholecystitis': 'Kolesistit',
        'cholangitis': 'Kolanjit',
        'biliary obstruction': 'Bilier Obstrüksiyon',
        'pancreatic cancer': 'Pankreas Kanseri',
        'pancreatitis': 'Pankreatit',
        'chronic pancreatitis': 'Kronik Pankreatit',
        'acute pancreatitis': 'Akut Pankreatit',
        'pancreatic insufficiency': 'Pankreatik Yetmezlik',
        'diabetes insipidus': 'Diabetes İnsipidus',
        'syndrome of inappropriate adh': 'Uygunsuz ADH Sendromu',
        'hypernatremia': 'Hipernatremi',
        'hyponatremia': 'Hiponatremi',
        'hyperkalemia': 'Hiperkalemi',
        'hypokalemia': 'Hipokalemi',
        'hypercalcemia': 'Hiperkalsemi',
        'hypocalcemia': 'Hipokalsemi',
        'hyperphosphatemia': 'Hiperfosfatemi',
        'hypophosphatemia': 'Hipofosfatemi',
        'hypermagnesemia': 'Hipermagnezemi',
        'hypomagnesemia': 'Hipomagnezemi',
        '5 users found this comment helpful': 'Geçersiz Veri',
        '65+years users found this comment helpful': 'Geçersiz Veri',
        'users found this comment helpful': 'Geçersiz Veri',
        '0</span> users found this comment helpful.': 'Geçersiz Veri',
        '12</span> users found this comment helpful.': 'Geçersiz Veri',
        '6</span> users found this comment helpful.': 'Geçersiz Veri',
        '24</span> users found this comment helpful.': 'Geçersiz Veri',
        '9</span> users found this comment helpful.': 'Geçersiz Veri',
        '1</span> users found this comment helpful.': 'Geçersiz Veri',
        '2</span> users found this comment helpful.': 'Geçersiz Veri',
        '3</span> users found this comment helpful.': 'Geçersiz Veri',
        '4</span> users found this comment helpful.': 'Geçersiz Veri',
        '5</span> users found this comment helpful.': 'Geçersiz Veri',
        '7</span> users found this comment helpful.': 'Geçersiz Veri',
        '8</span> users found this comment helpful.': 'Geçersiz Veri',
        '10</span> users found this comment helpful.': 'Geçersiz Veri',
        '11</span> users found this comment helpful.': 'Geçersiz Veri',
        '13</span> users found this comment helpful.': 'Geçersiz Veri',
        '14</span> users found this comment helpful.': 'Geçersiz Veri',
        '15</span> users found this comment helpful.': 'Geçersiz Veri',
        'Not listed/othe': 'Listede Yok / Diğer',
        'other': 'Diğer',
        'unknown': 'Bilinmeyen',
        'n/a': 'Belirtilmemiş',
        'na': 'Belirtilmemiş',
        'none': 'Yok',
        'off label use': 'Endikasyon Dışı Kullanım',
        'off-label use': 'Endikasyon Dışı Kullanım',
        'smoking cessation': 'Sigara Bırakma',
        'weight management': 'Kilo Yönetimi',
        'weight loss': 'Kilo Verme',
        'weight gain': 'Kilo Alma',
        'appetite stimulation': 'İştah Artırıcı',
        'appetite suppression': 'İştah Baskılayıcı',
        'eating disorders': 'Yeme Bozuklukları',
        'anorexia nervosa': 'Anoreksiya Nervoza',
        'bulimia nervosa': 'Bulimiya Nervoza',
        'binge eating disorder': 'Tıkma Niyetli Yeme Bozukluğu',
        'body dysmorphic disorder': 'Vücut Dismorfik Bozukluğu',
        'trichotillomania': 'Trikotillomani',
        'skin picking disorder': 'Deri Koparma Bozukluğu',
        'hoarding disorder': 'Biriktirme Bozukluğu',
        'tourette syndrome': 'Tourette Sendromu',
        'tic disorders': 'Tik Bozuklukları',
        'autism spectrum disorder': 'Otizm Spektrum Bozukluğu',
        'asperger syndrome': 'Asperger Sendromu',
        'intellectual disability': 'Zihinsel Engellilik',
        'developmental delay': 'Gelişimsel Gecikme',
        'learning disabilities': 'Öğrenme Güçlükleri',
        'dyslexia': 'Disleksi',
        'dysgraphia': 'Disgrafi',
        'dyscalculia': 'Diskalküli',
        'speech disorders': 'Konuşma Bozuklukları',
        'stuttering': 'Kekemelik',
        'aphasia': 'Afazi',
        'dysarthria': 'Dizartri',
        'apraxia': 'Apraksi',
        'hearing loss': 'İşitme Kaybı',
        'tinnitus': 'Kulak Çınlaması',
        'vertigo': 'Vertigo',
        'meniere disease': 'Meniere Hastalığı',
        'benign paroxysmal positional vertigo': 'Yangın Paroksismal Pozisyonel Vertigo',
        'labyrinthitis': 'Labirentit',
        'vestibular neuritis': 'Vestibüler Nörit',
        'motion sickness': 'Hareket Hastalığı',
        'seasickness': 'Deniz Tutması',
        'car sickness': 'Araba Tutması',
        'airsickness': 'Uçak Tutması',
        'morning sickness': 'Sabah Bulantısı',
        'hyperemesis gravidarum': 'Hiperemezis Gravidarum',
        'pregnancy': 'Hamilelik',
        'preterm labor': 'Erken Doğum',
        'postpartum depression': 'Doğum Sonrası Depresyon',
        'postpartum psychosis': 'Doğum Sonrası Psikoz',
        'breastfeeding': 'Emzirme',
        'lactation suppression': 'Süt Kesme',
        'galactorrhea': 'Galaktore',
        'mastitis': 'Mastit',
        'breast engorgement': 'Meme Şişmesi',
        'nipple pain': 'Meme Başı Ağrısı',
        'cracked nipples': 'Çatlamış Meme Başı',
        'blocked milk duct': 'Tıkanmış Süt Kanalı',
        'low milk supply': 'Düşük Süt Üretimi',
        'oversupply of milk': 'Aşırı Süt Üretimi',
        'acne': 'Akne',
        'eczema': 'Egzama',
        'psoriasis': 'Sedef Hastalığı',
        'dermatitis': 'Dermatit',
        'rosacea': 'Rozasea',
        'vitiligo': 'Vitiligo',
        'alopecia': 'Alopesi',
        'hair loss': 'Saç Dökülmesi',
        'dandruff': 'Kepek',
        'seborrheic dermatitis': 'Seboreik Dermatit',
        'contact dermatitis': 'Kontakt Dermatit',
        'atopic dermatitis': 'Atopik Dermatit',
        'urticaria': 'Ürtiker',
        'angioedema': 'Anjiyoödem',
        'cellulitis': 'Selülit',
        'impetigo': 'İmpetigo',
        'folliculitis': 'Folikülit',
        'boils': 'Çıban',
        'abscess': 'Apse',
        'carbuncle': 'Karbonkül',
        'furuncle': 'Furonkül',
        'warts': 'Siğil',
        'molluscum contagiosum': 'Molluskum Kontagiozum',
        'herpes simplex': 'Herpes Simpleks',
        'herpes zoster': 'Herpes Zoster',
        'shingles': 'Zona',
        'chickenpox': 'Suçiçeği',
        'measles': 'Kızamık',
        'rubella': 'Kızamıkçık',
        'mumps': 'Kabakulak',
        'whooping cough': 'Boğmaca',
        'diphtheria': 'Difteri',
        'tetanus': 'Tetanoz',
        'polio': 'Çocuk Felci',
        'meningitis': 'Menenjit',
        'encephalitis': 'Ensefalit',
        'pneumonia': 'Zatürre',
        'bronchitis': 'Bronşit',
        'asthma': 'Astım',
        'copd': 'KOAH',
        'emphysema': 'Amfizem',
        'tuberculosis': 'Tüberküloz',
        'pleurisy': 'Plörit',
        'pneumothorax': 'Pnömotoraks',
        'pulmonary embolism': 'Pulmoner Emboli',
        'sleep apnea': 'Uyku Apnesi',
        'snoring': 'Horlama',
        'insomnia': 'Uykusuzluk',
        'narcolepsy': 'Narkolepsi',
        'restless leg syndrome': 'Huzursuz Bacak Sendromu',
        'periodic limb movement': 'Periyodik Ekstremite Hareketi',
        'jet lag': 'Jet Lag',
        'shift work disorder': 'Vardiya Çalışma Bozukluğu',
        'circadian rhythm disorder': 'Sirkadiyen Ritim Bozukluğu',
        'seasonal affective disorder': 'Mevsimsel Duygudurum Bozukluğu',
        'premenstrual syndrome': 'Premenstrüel Sendrom',
        'premenstrual dysphoric disorder': 'Premenstrüel Disforik Bozukluk',
        'menopause': 'Menopoz',
        'perimenopause': 'Perimenopoz',
        'hot flashes': 'Sıcak Basması',
        'night sweats': 'Gece Terlemesi',
        'vaginal dryness': 'Vajinal Kuruluk',
        'vaginal atrophy': 'Vajinal Atrofi',
        'vaginitis': 'Vajinit',
        'yeast infection': 'Mantar Enfeksiyonu',
        'bacterial vaginosis': 'Bakteriyel Vajinoz',
        'urinary tract infection': 'İdrar Yolu Enfeksiyonu',
        'cystitis': 'Sistit',
        'pyelonephritis': 'Piyelonefrit',
        'kidney stones': 'Böbrek Taşı',
        'kidney disease': 'Böbrek Hastalığı',
        'chronic kidney disease': 'Kronik Böbrek Hastalığı',
        'acute kidney injury': 'Akut Böbrek Hasarı',
        'dialysis': 'Diyaliz',
        'transplant': 'Nakil',
        'organ rejection': 'Organ Reddi',
        'immunosuppression': 'İmmünosüpresyon',
        'autoimmune disease': 'Otoimmün Hastalık',
        'lupus': 'Lupus',
        'scleroderma': 'Skleroderma',
        'sjögren syndrome': 'Sjögren Sendromu',
        'vasculitis': 'Vaskülit',
        'polymyalgia rheumatica': 'Polimiyaljia Romatika',
        'giant cell arteritis': 'Dev Hücreli Arterit',
        'temporal arteritis': 'Temporal Arterit',
        'takayasu arteritis': 'Takayasu Arteriti',
        'kawasaki disease': 'Kawasaki Hastalığı',
        'henoch schönlein purpura': 'Henoch Schönlein Purpurası',
        'thrombocytopenia': 'Trombositopeni',
        'thrombocytosis': 'Trombositoz',
        'anemia': 'Anemi',
        'iron deficiency': 'Demir Eksikliği',
        'vitamin b12 deficiency': 'B12 Vitamini Eksikliği',
        'folate deficiency': 'Folat Eksikliği',
        'vitamin d deficiency': 'D Vitamini Eksikliği',
        'scurvy': 'Skorbüt',
        'rickets': 'Raşitizm',
        'osteomalacia': 'Osteomalazi',
        'osteoporosis': 'Osteoporoz',
        'osteopenia': 'Osteopeni',
        'paget disease': 'Paget Hastalığı',
        'osteomyelitis': 'Osteomiyelit',
        'septic arthritis': 'Septik Artrit',
        'gout': 'Gut',
        'pseudogout': 'Psödogut',
        'chondrocalcinosis': 'Kondrocalsinoz',
        'fibromyalgia': 'Fibromiyalji',
        'chronic fatigue syndrome': 'Kronik Yorgunluk Sendromu',
        'myofascial pain syndrome': 'Miyofasyal Ağrı Sendromu',
        'tension headache': 'Gerilim Baş Ağrısı',
        'cluster headache': 'Küme Baş Ağrısı',
        'trigeminal neuralgia': 'Trigeminal Nöralji',
        'bell palsy': 'Bell Felci',
        'carpal tunnel syndrome': 'Karpal Tünel Sendromu',
        'cubital tunnel syndrome': 'Kubital Tünel Sendromu',
        'tarsal tunnel syndrome': 'Tarsal Tünel Sendromu',
        'sciatica': 'Siyatik',
        'herniated disc': 'Disk Hernisi',
        'spinal stenosis': 'Spinal Stenoz',
        'spondylosis': 'Spondiloz',
        'spondylolisthesis': 'Spondilolistezis',
        'kyphosis': 'Kifoz',
        'lordosis': 'Lordoz',
        'scoliosis': 'Skolyoz',
        'whiplash': 'Boyun Burkulması',
        'concussion': 'Beyin Sarsıntısı',
        'traumatic brain injury': 'Travmatik Beyin Hasarı',
        'alzheimer disease': 'Alzheimer Hastalığı',
        'dementia': 'Demans',
        'vascular dementia': 'Vasküler Demans',
        'lewy body dementia': 'Lewy Cisimcikli Demans',
        'frontotemporal dementia': 'Frontotemporal Demans',
        'mild cognitive impairment': 'Hafif Bilişsel Bozukluk',
        'delirium': 'Deliryum',
        'sundowning': 'Gün Batımı Sendromu'
    }
    
    condition_lower = condition.lower().strip()
    
    if condition_lower in simple_translations:
        return simple_translations[condition_lower]
    
    print(f"ÇEVRİLEMEYEN HASTALIK: '{condition}' -> '{condition_lower}'")
    
    translated = condition_lower
    
    replacements = {
        'disorder': 'bozukluğu',
        'disease': 'hastalığı', 
        'syndrome': 'sendromu',
        'infection': 'enfeksiyonu',
        'cancer': 'kanseri',
        'pain': 'ağrısı',
        'prevention': 'önleme',
        'treatment': 'tedavisi',
        'therapy': 'terapisi',
        'deficiency': 'eksikliği',
        'insufficiency': 'yetmezliği',
        'failure': 'yetmezliği',
        'dysfunction': 'disfonksiyonu',
        'injury': 'yaralanması',
        'trauma': 'travması',
        'fracture': 'kırığı',
        'sprain': 'burkulması',
        'strain': 'gerilmesi',
        'inflammation': 'iltihaplanması',
        'swelling': 'şişmesi',
        'bleeding': 'kanaması',
        'hemorrhage': 'kanaması',
        'clot': 'pıhtısı',
        'embolism': 'embolisi',
        'thrombosis': 'trombozu',
        'stenosis': 'daralması',
        'obstruction': 'tıkanıklığı',
        'blockage': 'tıkanıklığı',
        'rupture': 'yırtılması',
        'perforation': 'delinmesi',
        'ulcer': 'ülseri',
        'erosion': 'erozyonu',
        'lesion': 'lezyonu',
        'tumor': 'tümörü',
        'mass': 'kitlesi',
        'cyst': 'kisti',
        'polyp': 'polipi',
        'nodule': 'nodülü',
        'growth': 'büyümesi',
        'enlargement': 'büyümesi',
        'hypertrophy': 'hipertrofisi',
        'atrophy': 'atrofisi',
        'degeneration': 'dejenerasyonu',
        'necrosis': 'nekrozu',
        'fibrosis': 'fibrozu',
        'sclerosis': 'sklerozu',
        'cirrhosis': 'sirozu',
        'edema': 'ödemi',
        'ascites': 'asiti',
        'effusion': 'efuzyonu',
        'congestion': 'konjesyonu',
        'ischemia': 'iskemisi',
        'infarction': 'enfarkti',
        'stroke': 'felci',
        'seizure': 'nöbeti',
        'spasm': 'spazmı',
        'cramp': 'krampı',
        'contracture': 'kontraktürü',
        'paralysis': 'felci',
        'weakness': 'zayıflığı',
        'fatigue': 'yorgunluğu',
        'malaise': 'halsizliği',
        'nausea': 'bulantısı',
        'vomiting': 'kusması',
        'diarrhea': 'ishali',
        'constipation': 'kabızlığı',
        'incontinence': 'kaçırması',
        'retention': 'retansiyonu',
        'urgency': 'aciliyeti',
        'frequency': 'sıklığı',
        'burning': 'yanması',
        'itching': 'kaşıntısı',
        'rash': 'döküntüsü',
        'hives': 'ürtikeri',
        'allergy': 'alerjisi',
        'sensitivity': 'duyarlılığı',
        'intolerance': 'intoleransı',
        'reaction': 'reaksiyonu',
        'response': 'yanıtı',
        'resistance': 'direnci',
        'immunity': 'bağışıklığı',
        'defect': 'defekti',
        'malformation': 'malformasyonu',
        'anomaly': 'anomalisi',
        'abnormality': 'anormalliği',
        'irregularity': 'düzensizliği',
        'disturbance': 'bozukluğu',
        'imbalance': 'dengesizliği',
        'instability': 'instabilitesi'
    }
    
    for eng, tr in replacements.items():
        if eng in translated:
            translated = translated.replace(eng, tr)

    if translated != condition_lower:
        return translated.title()
    
    return condition.title()

def compare_drugs(df: pd.DataFrame, drug1_name: str, drug2_name: str):
    """İki ilacı veri setine göre karşılaştırır - basit ve güvenilir."""
    try:
        drug1_data = df[df['drug_name'].str.lower() == drug1_name.lower()]
        drug2_data = df[df['drug_name'].str.lower() == drug2_name.lower()]

        if drug1_data.empty or drug2_data.empty:
            return None
        
        drug1_top_conditions = drug1_data['condition'].value_counts().head(3)
        drug2_top_conditions = drug2_data['condition'].value_counts().head(3)
        
        drug1_conditions_tr = {translate_condition_simple(cond): count for cond, count in drug1_top_conditions.items()}
        drug2_conditions_tr = {translate_condition_simple(cond): count for cond, count in drug2_top_conditions.items()}

        result = {
            drug1_name: {
                "average_rating": round(drug1_data['rating'].mean(), 2),
                "total_reviews": len(drug1_data),
                "top_conditions": drug1_conditions_tr
            },
            drug2_name: {
                "average_rating": round(drug2_data['rating'].mean(), 2),
                "total_reviews": len(drug2_data),
                "top_conditions": drug2_conditions_tr
            }
        }
        
        return result
        
    except Exception as e:
        print(f"İlaç karşılaştırma hatası: {e}")
        return None